version: '3.8'

services:
  chat-server:
    build: ./chat-server
    depends_on:
      - redis
      - kafka
      - cassandra
    environment:
      - REDIS_ADDR=redis:6379
      - KAFKA_BROKERS=kafka:9092
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_KEYSPACE=chat
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra_password

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_PASSWORD=cassandra_password
      - CASSANDRA_CLUSTER_NAME=chat-cluster
      - CASSANDRA_KEYSPACE=chat
