version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: auth_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: micro_db
      POSTGRES_USER: micro_user
      POSTGRES_PASSWORD: micro_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
