// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/admin/permission-approvals": {
            "patch": {
                "description": "관리자가 권한 요청을 승인 또는 거절합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "권한 승인 요청"
                ],
                "summary": "권한 요청 승인 또는 거절",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer JWT Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "권한 승인 또는 거절 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PermissionApprovalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/admin/permission-approvals-requests": {
            "get": {
                "description": "페이징을 지원하여 권한 요청 목록을 검색합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "권한 승인 요청"
                ],
                "summary": "권한 승인 요청 목록 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "페이지 번호 (기본값: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "페이지당 항목 수 (기본값: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.PermissionApprovalsRequestsPagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/admin/permission-groups": {
            "get": {
                "description": "모든 사용자 권한 그룹을 검색합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "사용자"
                ],
                "summary": "사용자 권한 그룹 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.PermissionGroups"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/admin/permissions": {
            "get": {
                "description": "모든 사용자 권한을 검색합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "사용자"
                ],
                "summary": "사용자 권한 목록 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Permission"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            },
            "post": {
                "description": "특정 계정에 대한 사용자 권한을 요청합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "사용자"
                ],
                "summary": "사용자 권한 요청",
                "parameters": [
                    {
                        "type": "string",
                        "description": "사용자 계정",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "권한 ID",
                        "name": "permission",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "새로운 요소 생성",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/admin/user": {
            "post": {
                "description": "새로운 사용자 계정을 생성하고 JWT 토큰을 반환합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "사용자"
                ],
                "summary": "사용자 계정 생성",
                "parameters": [
                    {
                        "description": "사용자 계정 생성 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserInsertRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.TokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/franchise-user-leads": {
            "get": {
                "description": "페이징을 지원하여 가맹점 문의 목록을 가져옵니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "가맹점 문의"
                ],
                "summary": "가맹점 문의 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer JWT Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "페이지 번호 (기본값: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "페이지당 항목 수 (기본값: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.FranchiseUserLeadsPagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            },
            "post": {
                "description": "새로운 가맹점 문의를 추가합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "가맹점 문의"
                ],
                "summary": "가맹점 문의 삽입",
                "parameters": [
                    {
                        "description": "가맹점 문의 요청 데이터",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FranchiseUserLeads"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.FranchiseUserLeadsInsertResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            },
            "delete": {
                "description": "가맹점 문의 데이터를 삭제 상태로 업데이트합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "가맹점 문의"
                ],
                "summary": "가맹점 문의 삭제",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer JWT Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "삭제할 가맹점 문의 ID 목록",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteFranchiseUserLeadsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.DeleteFranchiseUserLeadsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "description": "사용자를 인증하고 권한 정보와 JWT 토큰을 반환합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "사용자"
                ],
                "summary": "사용자 로그인",
                "parameters": [
                    {
                        "description": "사용자 로그인 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/menu": {
            "get": {
                "description": "사용자 권한 및 그룹 필터에 따라 메뉴 목록을 검색합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "메뉴"
                ],
                "summary": "메뉴 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003ctoken\u003e",
                        "description": "Bearer JWT Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "메뉴 항목 필터링을 위한 그룹 식별 코드",
                        "name": "group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "메뉴 항목 목록",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MenuItem"
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/v1/test": {
            "get": {
                "description": "쿼리 파라미터에 따라 지점별 description meta 태그를 반환합니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "지점"
                ],
                "summary": "지점 meta 태그 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "지점명 (예: gangnam)",
                        "name": "branch",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "meta 태그 HTML 반환",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "서버 오류",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DeleteFranchiseUserLeadsRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.DeleteFranchiseUserLeadsResponse": {
            "type": "object",
            "properties": {
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "models.ErrorResponse400": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse500": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.FranchiseUserLeads": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "branch_location": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inquiry": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "models.FranchiseUserLeadsInsertResponse": {
            "type": "object",
            "properties": {
                "inserted_id": {
                    "type": "integer"
                }
            }
        },
        "models.FranchiseUserLeadsPagination": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "inquiries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FranchiseUserLeads"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "approved_count": {
                    "type": "integer"
                },
                "pending_count": {
                    "type": "integer"
                },
                "rejected_count": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.MenuItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.Permission": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.PermissionApprovalRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "request_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "default": "approved",
                    "enum": [
                        "approved",
                        "rejected"
                    ],
                    "example": "approved"
                }
            }
        },
        "models.PermissionApprovalsRequests": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "requested_at": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.PermissionApprovalsRequestsPagination": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PermissionApprovalsRequests"
                    }
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.PermissionGroups": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "` + "`" + `omitempty` + "`" + `: 값이 없을 경우 JSON에서 제외"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.UserInsertRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api-hub.ppeum.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API-HUB",
	Description:      "API 제공 HUB 입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
